package com.abhinav.agentic_ai_chatbot.dto;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(
        description = "Response returned by the Agentic AI Enterprise Chatbot"
)
public class ChatResponse {

    @Schema(
            description = "Final answer generated by the selected processing path",
            example = "Employee details retrieved successfully."
    )
    private String answer;

    @Schema(
            description = "Source or tool used to process the request",
            example = "Employee Database"
    )
    private String source;

    @Schema(
            description = "Processing route selected by the Supervisor Agent",
            example = "DATABASE",
            allowableValues = {
                    "DATABASE",
                    "RAG",
                    "WEB_SEARCH",
                    "GENERAL",
                    "VALIDATION_ERROR",
                    "INTERNAL_ERROR"
            }
    )
    private String type;

    @Schema(
            description = "Indicates whether the request was successfully processed",
            example = "true"
    )
    private boolean success;

    @Schema(
            description = "Route-specific response data. Can contain employee records, RAG documents, or web search results.",
            nullable = true
    )
    private Object data;

    public ChatResponse() {
    }

    public ChatResponse(
            String answer,
            String source,
            String type,
            boolean success,
            Object data) {

        this.answer = answer;
        this.source = source;
        this.type = type;
        this.success = success;
        this.data = data;
    }

    public String getAnswer() {
        return answer;
    }

    public void setAnswer(String answer) {
        this.answer = answer;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public boolean isSuccess() {
        return success;
    }

    public void setSuccess(boolean success) {
        this.success = success;
    }

    public Object getData() {
        return data;
    }

    public void setData(Object data) {
        this.data = data;
    }
}