spring.application.name=agentic-ai-chatbot

# ===============================
# MySQL Database
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/agentic_ai
spring.datasource.username=root
spring.datasource.password=9440704606@aA

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Groq / Spring AI
# ===============================
spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai/v1
spring.ai.openai.chat.model=qwen/qwen3.8-27b

# ===============================
# Server
# ===============================
server.port=8080